kind: Service
apiVersion: v1
metadata:
    name: spark-master
spec:
    ports:
        - port: 7077
          name: spark
        - port: 8080
          name: webui
        - port: 10001
          name: driver
        - port: 10002
          name: block
    selector:
        app: spark-master
