kind: Service
apiVersion: v1
metadata:
    name: spark-driver
spec:
    ports:
        - port: 10000
          targetPort: 10000
          name: worker
        - port: 10001
          targetPort: 10001
          name: driver
        - port: 10002
          targetPort: 10002
          name: blockmanager
    selector:
        app: spark-driver
